# Generated by Django 6.0.3 on 2026-03-17 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_sobrecargo', models.IntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.prestamo')),
            ],
        ),
    ]
