# Generated by Django 6.0.3 on 2026-03-19 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_multa_prestamo_alter_prestamo_libro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente de Aprobación'), ('A', 'Activo / Entregado'), ('D', 'Esperando Recepción Staff'), ('F', 'Finalizado / Devuelto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='staff_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
